### ISSUE TITLE
Is MaxVendorId missing in Publisher Restrictions Section ?

### ISSUE THREAD

**Issue by mdenison** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#115]
Having a look at https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#the-core-string 

In the "Vendor Legitimate Interest Section" as well in the "Vendor Consent Section" there is a "MaxVendorId" defined which defines the last part of an RangeEntry. 

I am trying to figure out where the "Publisher Restrictions Section" RangeEntrys actually end or how to determine the end? 

Many thanks in advance.

**Comment by mdenison** [comment]
Maybe I was misinterpreting the description of MaxVendorId: "Because this section can be a variable length, this indicates the last ID of the section so that a decoder will know when it has reached the end."  

Is the MaxVendorId the end of the section, only if it is a BitField? And has nothing to do with the RangeEntrys? Thus a RangeEntry is always either 17 Bit (1 Bit for IsARange, 16 Bit StartOrOnlyVendorId) or 33 Bit (1 Bit for IsARange, 16 Bit StartOrOnlyVendorId and 16 Bit for the EndVendorId) ?

**Comment by chrispaterson** [comment]
There is not a "MaxVendorId" on the publisher restrictions.  There is a "Num Publisher Restrictions" and since a publisher restriction is a finite set of Purpose ID and Restriction type, the vendors grouped under that restriction are handled as a range entry and never a bitfield.  Range Entries each have their own length field.
