### ISSUE TITLE
Consent String Representing No Consent

### ISSUE THREAD

**Issue by GLStephen** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#159]
Is there an example of a V1 or V2 string that represents a blanket "no consent" status?

**Comment by wittjill** [comment]
@GLStephen  you can use this tool to generate consent strings https://iabtcf.com/#/encode

**Comment by GLStephen** [comment]
@wittjill I understand that, but there is a lack of positive assertion that the default state of that page is a blanket no consent, which was the goal of my question.

**Comment by chrispaterson** [comment]
Do you feel there is a "lack of positive assertion" because when you go to the view decoded page the vendor consent vector is not there?  Others have mentioned this, so I'm checking if this is your concern as well?  (When I wrote the page, I assumed people would know if it's not there then there is no consent – but maybe that's not a good assumption)

**Comment by GLStephen** [comment]
@chrispaterson assuming the string could be used for some valid purpose, like a very paranoid fallback in the case of indeterminate CMP behavior (or some other myriad things that might come up) I would just want to be sure that the string generated would be interpreted by the upstream vendors, and ultimately a legal authority, as representing a blanket no consent.

**Comment by chrispaterson** [comment]
With the TCF the absence of a signal is "no consent" whether there is no string at all or the signal is an explicit false.  The String is designed that way so that the encoding can be variable length.
