### ISSUE TITLE
IAB Tech Lab - CMP API v2 - vendorListVersion

### ISSUE THREAD

**Issue by skoklowski** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#177]
Hi,

I wonder why `vendorListVersion` field is absent in [TCData](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#tcdata) and [InAppTCData](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#inapptcdata) objects? It's strange because even `cmpVersion` field is present.

Publishers may decide to capture new consent depending not only on `tcfPolicyVersion` but also `vendorListVersion` stored in consent string compared to `vendorListVersion` provided by current vendor list. But it is impossible to determine `vendorListVersion` stored in consent string because `getTCData` command doesn't return this value.

**Comment by chrispaterson** [comment]
`TCData` is oriented toward the consumption of vendors and not the publisher.  The CMP make the determination of whether or not to show the UI to the user and is the entity that detects the difference between GVL versions.  The publisher hires or creates a CMP to manage that for them.

**Comment by skoklowski** [comment]
OK, I understand.

But even then `vendorListVersion` may be useful for vendors. For example vendor may add declaration of new purposes at some point. Of course this should be done by publishing new version of global vendor list. By obtaining `vendorListVersion` from `__tcfapi` such vendor may determine whether it is allowed to use these new purposes or not. I assume that vendor mustn't use these new purposes when `vendorListVersion` (that could be returned by `__tcfapi`) is older than version in which vendor declared new purposes on global vendor list.

I'm not sure if this is only theoretical issue or real one.

**Comment by asr-enid** [comment]
@chrispaterson - I think @skoklowski is referring to the usage of a vendor. 

A vendor calling
>__tcfapi('getTCData', 2, (tcData, success) ..

gets passed TCData 

> TCData = {
  tcString: 'base64url-encoded TC string with segments',
  tcfPolicyVersion: 2,
  cmpId:1000,
  cmpVersion: 1000,
.....

in order to understand which version of the GVL was used by the CMP with the current definition of _TCData_ he would need to decode the tcString and extract _vendorListVersion_ from it. 

I would be more convenient to extend TCData 
> TCData = {
  tcString: 'base64url-encoded TC string with segments',
  tcfPolicyVersion: 2,
  cmpId:1000,
  cmpVersion: 1000,
 **vendorListVersion: 32**
