### ISSUE TITLE
Supported Language List

### ISSUE THREAD

**Issue by danielrsantana** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#91]
I've tried to find but I didn't. Question is: is there a list of supported languages for vendors and purposes ?

Thank you

**Comment by jgalisteo** [comment]
I found a list of supported languages in this [section](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#translations-for-purposes-special-purposes-features-and-special-features).

The problem is that the url to get a specific language is not working, for example:

- https://vendorlist.consensu.org/v2/purposes-es.json
- https://vendorlist.consensu.org/v2/purposes-fr.json

The section points to a list for v1, is there any place where the list for v2 can be found?

**Comment by wittjill** [comment]
this will include v2 when they are available, should be this week: https://register.consensu.org/Translation
